### ISSUE TITLE
Illegal characters>?? Could not create dist folder

### ISSUE THREAD

**Issue by tenghanc** [kazuki-sf/YouTube_Summary_with_ChatGPT#10]
> youtube_summary_with_chatgpt@1.0.0 build
> npm run clean && webpack

> youtube_summary_with_chatgpt@1.0.0 clean
> rimraf dist/*

Error: Illegal characters in path.
    at pathArg (C:\Users\Psle\AppData\Roaming\npm\node_modules\rimraf\dist\cjs\src\path-arg.js:45:33)
    at C:\Users\Psle\AppData\Roaming\npm\node_modules\rimraf\dist\cjs\src\index.js:40:80
    at Array.map (<anonymous>)
    at C:\Users\Psle\AppData\Roaming\npm\node_modules\rimraf\dist\cjs\src\index.js:40:42
    at main (C:\Users\Psle\AppData\Roaming\npm\node_modules\rimraf\dist\cjs\src\bin.js:242:15)
    at Object.<anonymous> (C:\Users\Psle\AppData\Roaming\npm\node_modules\rimraf\dist\cjs\src\bin.js:252:5)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  path: 'C:\\Users\\Psle\\YouTube_Summary_with_ChatGPT\\dist\\*',
  code: 'EINVAL'
}

**Comment by kazuki-sf** [comment]
Please try `npm run build` instead :)
